services:
  - type: web
    name: certificateapp
    env: node
    region: singapore
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: file:./dev.db
